export const FETCH_SPECIALIZATIONS_REQUEST = "FETCH_SPECIALIZATIONS_REQUEST";
export const FETCH_SPECIALIZATIONS_SUCCESS = "FETCH_SPECIALIZATIONS_SUCCESS";
export const FETCH_SPECIALIZATIONS_FAILURE = "FETCH_SPECIALIZATIONS_FAILURE";

export const FETCH_EDUCATION_REQUEST = "FETCH_EDUCATION_REQUEST";
export const FETCH_EDUCATION_SUCCESS = "FETCH_EDUCATION_SUCCESS";
export const FETCH_EDUCATION_FAILURE = "FETCH_EDUCATION_FAILURE";
