export const SHOW_CHANGE_PAGE = "SHOW_CHANGE_PAGE";
export const IS_PROFILE_EDITING = "IS_PROFILE_EDITING";
export const SET_PROFILE_DATA_IN_SIDEBAR = "SET_PROFILE_DATA_IN_SIDEBAR";
export const FETCH_CLASSES_FAILURE = "FETCH_CLASSES_FAILURE";
export const FETCH_CLASSES_SUCCESS = "FETCH_CLASSES_SUCCESS";
export const FETCH_CLASSES_REQUEST = "FETCH_CLASSES_REQUEST";

export const FETCH_SUBJECTS_AND_CLASSES_REQUEST =
  "FETCH_SUBJECTS_AND_CLASSES_REQUEST";
export const FETCH_SUBJECTS_AND_CLASSES_SUCCESS =
  "FETCH_SUBJECTS_AND_CLASSES_SUCCESS";
export const FETCH_SUBJECTS_AND_CLASSES_FAILURE =
  "FETCH_SUBJECTS_AND_CLASSES_FAILURE";
