export const FETCH_ASSISTANTS_REQUEST = "FETCH_ASSISTANTS_REQUEST";
export const FETCH_ASSISTANTS_SUCCESS = "FETCH_ASSISTANTS_SUCCESS";
export const FETCH_ASSISTANTS_FAILURE = "FETCH_ASSISTANTS_FAILURE";

export const ADD_ASSISTANTS_REQUEST = "ADD_ASSISTANTS_REQUEST";
export const ADD_ASSISTANTS_SUCCESS = "ADD_ASSISTANTS_SUCCESS";
export const ADD_ASSISTANTS_FAILURE = "ADD_ASSISTANTS_FAILURE";

export const HANDLE_DELETE = "HANDLE_DELETE";
