export const USERS_IN_ADMIN_PAGE = "USERS_IN_ADMIN_PAGE";
export const HANDLE_ADMIN_PAGE_CHANGE = "HANDLE_ADMIN_PAGE_CHANGE";
export const OPEN_RIGHT_SIDEBAR_IN_ADMIN_PAGE = "OPEN_RIGHT_SIDEBAR_IN_ADMIN_PAGE";
export const FETCH_ALL_CLASSES_SUCCESS = "FETCH_ALL_CLASSES_SUCCESS";
export const FETCH_ALL_CLASSES_FAILURE = "FETCH_ALL_CLASSES_FAILURE";
export const FETCH_FILTER_ADMIN_PAGE_SUCCESS = "FETCH_FILTER_ADMIN_PAGE_SUCCESS";
export const SUCCESS_ADMIN_NOTIFICATION = "SUCCESS_ADMIN_NOTIFICATION";
