export const FETCH_HOME_DETAILS_REQUEST = "FETCH_HOME_DETAILS_REQUEST";
export const FETCH_HOME_DETAILS_SUCCESS = "FETCH_HOME_DETAILS_SUCCESS";
export const FETCH_HOME_DETAILS_FAILURE = "FETCH_HOME_DETAILS_FAILURE";

export const FETCH_TABLE_LSNPLAN_DETAILS_REQUEST =
  "FETCH_TABLE_LSNPLAN_DETAILS_REQUEST";
export const FETCH_TABLE_LSNPLAN_DETAILS_SUCCESS =
  "FETCH_TABLE_LSNPLAN_DETAILS_SUCCESS";
export const FETCH_TABLE_LSNPLAN_DETAILS_FAILURE =
  "FETCH_TABLE_LSNPLAN_DETAILS_FAILURE";

export const HANDLE_HOME_CHANGE = 'HANDLE_HOME_CHANGE';
